version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: flowbit-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - flowbit-network

  api:
    build: ./packages/api
    container_name: flowbit-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/flowbit?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - WEBHOOK_SECRET=webhook-secret-shared-with-n8n
    depends_on:
      - mongodb
    volumes:
      - ./packages/api:/app
      - /app/node_modules
    networks:
      - flowbit-network

  shell:
    build: ./packages/shell
    container_name: flowbit-shell
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./packages/shell:/app
      - /app/node_modules
    networks:
      - flowbit-network

  support-tickets-app:
    build: ./packages/support-tickets-app
    container_name: flowbit-support-tickets-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./packages/support-tickets-app:/app
      - /app/node_modules
    networks:
      - flowbit-network

  n8n:
    image: n8nio/n8n:latest
    container_name: flowbit-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://api:3001
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - flowbit-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: flowbit-ngrok
    restart: unless-stopped
    command: ["http", "api:3001"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN:-}
    depends_on:
      - api
    networks:
      - flowbit-network

volumes:
  mongodb_data:
  n8n_data:

networks:
  flowbit-network:
    driver: bridge